config/routes.rb
Rails.application.routes.draw do
 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'about_us/index'

  # get 'enquires/index'

 get 'faqs/index'

 get 'terms/index'

 get 'abouts/index'

 get 'messages/new'

 devise_for :users
 resources :properties
 resources :homes
 resources :messages
 resources :accounts
 resources :abouts
 resources :contacts
 resources :properties
 resources :categories
 resources :enquirey
 resources :enquiries

 
 # namespace :admin do
 # 	resources :categories, only: [:index, :update, :edit, :new, :create], controller: '/admin/categories', action:'new' 
 # 	resources :admins
 # 	resources :properties, only: [:index, :update, :edit, :new]

 # end

 get 'accounts/user'

 root "homes#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :properties
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/enquirey.rb
class Enquirey < ApplicationRecord
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord

	def full_name
	  self.first_name + self.last_name
	end
end

app/models/news_feed.rb
class NewsFeed < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :category

  mount_uploader :image, ImageUploader

  validates_processing_of :image
  
  

  enum status: [:active, :inactive]
  ENUM_ENTITY = {"active" => 1, "inactive" => 0}

  scope :property, lambda{|property| where("concat(city, bhk, price) like ?", "%#{property}%").presence || all }

  # def self.search(search)
  # 	if search
  # 		where('locality LIKE ?', "%#{search}%")
  #     # Property.where('city ILIKE :query OR bhk ILIKE :query OR price ILIKE :query', query: "%#{query}%")

  # 		# where('city LIKE ? ', "%#{property}%").having("expenses.category = 1")
  # 	else
  # 		all
  # 	end
  # end

  def self.search(search)
    # where("locality LIKE ?", "%#{search}%").having("properties.status = 1")
    where("locality LIKE ?", "%#{search}%")
  end


  private
	
	def image_size_validation
	   errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
	end
end

app/models/query.rb
class Query < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/enquirey_controller.rb
class EnquireyController < ApplicationController
   before_action :set_new_query
  
  def index

  end

  def create
  	@query = Query.new(query_params)

  	p '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
  	p @query
  	p '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
  	respond_to do |format|
  		if @query.save
  			format.json {render json: @query, status: :ok}
  			format.js {redirect_to root_path }
  			format.html {redirect_to homes_path, flash: {success: "Message Send Successfully"}}
  		else
  			format.json {render json: @query.errors.full_messages, status: :unprocessable_entity}
  			format.js
  			format.html {redirect_to homes_path, flash: {error: @query.errors.full_messages}}
  		end
  	end
  end


  private

  def set_new_query
  	@query = Query.new 
  end

  def query_params
  	params.require(:query).permit(:name,:phone,:locality,:user_id,:purpose)
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/enquires_helper.rb
module EnquiresHelper
end

app/helpers/enquirey_helper.rb
module EnquireyHelper
end

app/helpers/enquiry_helper.rb
module EnquiryHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/enquirey/_form.html.erb
<div>
<div class="row">
    <div class="col-md-10 col-md-offset-1 col-sm-12 text-center page-title">
        <!-- /.feature title -->
        <h2>Enquirey</h2> 
    </div>
</div>
<div class="content-area recent-property padding-top-40" style="background-color: #FFF;">
    <div class="container">  
        <div class="row">
            <div class="col-md-8 col-md-offset-2"> 
                <div class="" id="contact1">                        
                    <%#= form_for :enquirey do |e| %>
                    <%#= form_for :enquirey, html: {class: 'enquirey_form'}, method: :post, remote: true do |e| %>
                    <%= form_for (:query), url: enquirey_index_path(@query), html: {class: 'finance_form'}, method: :post, remote: true do |e| %>


                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="firstname">Name</label>
                                    <!-- <input type="text" class="form-control" id="firstname"> -->
                                    <%= e.text_field :name, class: "form-control", required: true%>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <%= e.label :phone, "Mobile No"%>
                                    <%= e.text_field :phone, class: "form-control", id: 'phone', required: true, maxlength: 10%>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="email">locality</label>
                                    <%= e.text_field :locality, class: "form-control", required: true%>
                                    <!-- <input type="text" class="form-control" id="email"> -->
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="subject">Message</label>
                                    <!-- <textarea type="text" class="form-control" id="subject"></textarea> -->
                                    <%= e.text_area :purpose, class: "form-control", required: true%>
                                </div>
                            </div>
                            <div class="submit">
                                <%= e.submit "Send Message", class: "btn btn-primary"%>
                                <!-- <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Send message</button> -->
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>    
        </div>
    </div>
</div>

app/views/enquirey/create.js.erb
<% if @query.errors.empty? %>
  $('.query_form')[0].reset();
  $('#ModalAddFinance').modal('hide');
    toastr["success"]('Message has been send successfully.')
   setTimeout(function(){
    window.location.reload(true);
    }, 2000);
<%else%>
  $('.errors_query').append('<p class = "error_msg" ><%= @query.errors.full_messages.join(' , ') %></p>');
  setTimeout(function(){
      $('.error_msg').remove();
    }, 3000);
<%end%>

app/views/enquirey/index.html.erb
<h1>Enquires#index</h1>
<p>Find me in app/views/enquires/index.html.erb</p>