config/routes.rb
Rails.application.routes.draw do
 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'about_us/index'

  # get 'enquires/index'

 get 'faqs/index'

 get 'terms/index'

 get 'abouts/index'

 get 'messages/new'

 devise_for :users
 resources :properties
 resources :homes
 resources :messages
 resources :accounts
 resources :abouts
 resources :contacts
 resources :properties
 resources :categories
 resources :enquirey
 resources :enquiries

 
 # namespace :admin do
 # 	resources :categories, only: [:index, :update, :edit, :new, :create], controller: '/admin/categories', action:'new' 
 # 	resources :admins
 # 	resources :properties, only: [:index, :update, :edit, :new]

 # end

 get 'accounts/user'

 root "homes#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :properties
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/enquirey.rb
class Enquirey < ApplicationRecord
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord

	def full_name
	  self.first_name + self.last_name
	end
end

app/models/news_feed.rb
class NewsFeed < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :category

  mount_uploader :image, ImageUploader

  validates_processing_of :image
  
  

  enum status: [:active, :inactive]
  ENUM_ENTITY = {"active" => 1, "inactive" => 0}

  scope :property, lambda{|property| where("concat(city, bhk, price) like ?", "%#{property}%").presence || all }

  # def self.search(search)
  # 	if search
  # 		where('locality LIKE ?', "%#{search}%")
  #     # Property.where('city ILIKE :query OR bhk ILIKE :query OR price ILIKE :query', query: "%#{query}%")

  # 		# where('city LIKE ? ', "%#{property}%").having("expenses.category = 1")
  # 	else
  # 		all
  # 	end
  # end

  def self.search(search)
    # where("locality LIKE ?", "%#{search}%").having("properties.status = 1")
    where("locality LIKE ?", "%#{search}%")
  end


  private
	
	def image_size_validation
	   errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
	end
end

app/models/query.rb
class Query < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  
  # before_action :set_new_property
  
  def index
    @search = Property.ransack(params[:q])
    @search.sorts = 'created_at asc' if @search.sorts.empty?
    @search.sorts = 'price asc' if @search.sorts.empty?
    properties = Property.search(params[:search])
    properties = Property.property if params[:search] == "property"
    properties = Property.all if params[:search].nil?
    @properties = properties.page(params[:page]).per_page(6).order("created_at DESC")
      respond_to do |format|
        format.json {render json: @properties, status: :ok }
        format.js
        format.html
      end
  end

  def show
    @property = Property.find(params[:id])
    respond_to do |format|
      format.html
      format.js
      format.json {render json: @property, status: :ok}
    end
  end

  def create
  	@properties = Property.new(property_params)
  	respond_to do |format|
  	  if @properties.save
  	  	format.json {render json: @properties, status: :ok }
  	  	format.js
  	  	format.html {redirect_to properties_path, flash: {success: "Property Saved successfully" }}
  	  else
  	  	format.json {render json: @properties.errors.full_messages, status: :unprocessable_entity}
  	  	format.js
  	  	format.html {redirect_to properties_path, flash: {error: @properties.errors.full_messages}}
  	  end
  	end
  end

  # private

  # def property_params
  # 	params.require(:property).permit(:name,:desc,:price,:price_sqft,:bhk,:size,:city,:start_date,:end_date,:status,:property_status,:bathroom,:bedroom,:toilet,:property_type,:sales_type,:project_address,:image,:builder_name,:category_id)
  # end

  # def set_new_property
  # 	@property = Property.new
  # end


end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/enquires_helper.rb
module EnquiresHelper
end

app/helpers/enquirey_helper.rb
module EnquireyHelper
end

app/helpers/enquiry_helper.rb
module EnquiryHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/__admin/properties/1index.html.erb
<%= render 'property2'%>
<%#= link_to "New Category", new_category_path %>
<%#= link_to "New Property", new_property_path %>

<!-- <h2>Properties</h2> -->
<!-- <table>
	<thead>
		<tr>
			<th>Project Name</th>
			<th>Project Type</th>
			<th>Price</th>
			<th>Price/Sqft</th>
			<th>BHK</th>
			<th>Image</th>
			<th>Size</th>
		</tr>
	</thead>
	<tbody>
		<%# for property in @properties %>
		  <tr>
			<td><%#= property.name%></td>
			<td><%# category = Category.find_by(id: property.category_id)%><%#= category.name%></td>
			<td><%#= property.price%></td>
			<td><%#= property.price_sqft%></td>
			<td><%#= property.bhk %></td>
			<td><%#= image_tag property.image_url(:thumb)%></td>
			<td><%#= property.size%></td>
		  </tr>
		<%# end %>
	</tbody>
</table> -->

app/views/__admin/properties/_form.html.erb
<%= form_for @property do |pr| %>
	<div>
		<%= pr.label :name, "Property Name"%>
		<%= pr.text_field :name, required: true %>
	</div>

	<div>
		<%= pr.label :category_id, "Property Type"%>
		<%= pr.select :category_id, Category.order("name ASC").map {|pt| [pt.name, pt.id]},:prompt =>"Select Category", required: true %>
	</div>

	<div>
		<%= pr.label :desc, "Description" %>
		<%= pr.text_field :desc ,required: true %>
	</div>

	<div>
		<%= pr.label :price, "Price" %>
		<%= pr.number_field :price, required: true %>
	</div>

	<div>
		<%= pr.label :size, "Size" %>
		<%= pr.text_field :size, required: true, :placeholder=>"100-200 sqft"%>
	</div>

	<div>
		<%= pr.label :price_sqft, "Price/Sqft"%>
		<%= pr.text_field :price_sqft, required: true, :placeholder=>"price per sqft" %>
	</div>

	<div>
		<%= pr.label :bhk, "BHK" %>
		<%= pr.text_field :bhk, required: true, :placeholder=>"1 BHK"%>
	</div>

	<div>
		<%= pr.label :city, "City"%>
		<%= pr.text_field :city, required: true %>
	</div>

	<div>
		<%= pr.label :status, "Status"%>
		<%= pr.text_field :status%>
	</div>


	<div>
		<%= pr.label :sales_type, "Sales Type" %>
		<%= pr.text_field :sales_type, required: true %>
	</div>

	<div>
		<%= pr.label :project_address, "Project Address"%>
		<%= pr.text_field :project_address, required: true%>
	</div>

	<div>
		<%= pr.label :image, "Property Image"%>
		<%= pr.file_field :image, required: true %>
		<% if pr.object.image? %>
		  <%= image_tag pr.object.image.thumb.url %>
		  <%= pr.label :remove_image %>
		  <%= pr.check_box :remove_image %>
		<% end %>
	</div>

	<div>
		<%= pr.label :builder_name, "Builder Name"%>
		<%= pr.text_field :builder_name,required: true%>
	</div>

	<div>
		<%= pr.submit "Save"%>
	</div>

<% end %>


 <script>
  $( function() {
    $( ".datepicker" ).datepicker();
  } );
  </script>

app/views/__admin/properties/_form2.html.erb
<div class="content-area blog-page padding-top-40" style="background-color: #FCFCFC; padding-bottom: 55px;">
    <div class="container">
        <h4 class="info-text"> New Property </h4>
        <%= form_for @property do |pr| %>
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-3">
                        <div class="form-group">
                           <%= pr.label :name, "Property Name:"%>
                           <%= pr.text_field :name ,required: true, class: "form-control" %>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :size, "Sqft:"%>
                            <%= pr.text_field :size, class: "form-control"%>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :price, "Price"%>
                            <%= pr.text_field :price, class: "form-control" %>
                        </div>
                    </div>

                     <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :category_id, "Property Type"%>
                            <%= pr.select :category_id, Category.order("name ASC").map {|pt| [pt.name, pt.id]},class: "form-control", :prompt =>"--Select--" %> </span>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :price_sqft, "Price/Per Sqft:" %>
                            <%= pr.text_field :price_sqft, class: "form-control"%>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :bhk, "BHK:" %>
                            <%= pr.text_field :bhk, class: "form-control"%>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :city, "City:" %>
                            <%= pr.text_field :city, class: "form-control"%>
                        </div>
                    </div>
                </div>
            </div>
        <hr>
        <h4>Building Details:</h4>
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :status, "Project Status" %>
                            <%= pr.text_field :status, class: "form-control"%>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :sales_type, "Sale Type:" %>
                            <%= pr.text_field :sales_type, class: "form-control"%>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :builder_name, "Builder Name:" %>
                            <%= pr.text_field :builder_name, class: "form-control"%>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :project_address, "Project Address:" %>
                            <%= pr.text_field :project_address, class: "form-control"%>
                        </div>
                    </div>
                </div>
            </div>
            
            
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <%= pr.label :desc, "Property Description:"%>
                            <%= pr.text_field :desc, class: "form-control"%>
                        </div>
                    </div>
                <!-- </div> -->
                    <div class="col-sm-3">
                        <div class="form-group">
                            <%= pr.label :image, "Property Image"%>
                            <%= pr.file_field :image, required: true, class: "form-control" %>
                            <% if pr.object.image? %>
                              <%= image_tag pr.object.image.thumb.url %>
                              <%= pr.label :remove_image %>
                              <%= pr.check_box :remove_image %>
                            <% end %>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <!-- <div class="form-group"> -->
                            <div class="submit">
                                <%= pr.submit "Create", class: 'navbar-btn nav-button wow bounceInRight'  %>
                              <%#= pr.submit 'Save'%>
                            </div>                
                        <!-- </div> -->
                        
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

<style>
    .submit{
        width: 87px;
    padding-top: 21px;
    margin-left: 29%;
    margin-bottom: 10%;
    }
</style>

app/views/__admin/properties/_table.html.erb
<div class="">
    <div class="title-line wow fadeInRight animated"></div>
</div>
<div class="row wow fadeInRight animated">
    <div class="col-sm-6">
        <p class="author-category">
            <a href="#">Properties</a>
        </p>
    </div>
    <div class="col-sm-6 right" >
            <div><%= link_to "New Property", new_admin_property_path %></div>
        <!-- <p class="date-comments">
            <a href="single.html"><i class="fa fa-comment-o"></i> 8 Comments</a>
        </p> -->
    </div>
</div> 



<table border=1 style="text-align: center; width: 310%;">
	<tr>
		<th>Project Name</th>
		<th>Project Type</th>
		<th>Price</th>
		<th>BHK</th>
		<th>Size</th>
		<th>Status</th>
		<th>Created_at</th>
		<th>Action</th>
	</tr>
	<% for property in @properties %>
    <tr>
    	<tr>
	   		<td><%= link_to h(property.name),edit_admin_property_path(property)%></td>
	   		<td><% category = Category.find_by(id: property.category_id)%><%= category.name%></td>
	   		<td><%= property.price%></td>
	   		<td><%= property.bhk %></td>
	   		<td><%= property.size%></td>
	   		<td><%= property.status%></td>
	   		<td><%= property.created_at%></td>
	   		<td>
	   		</td>
	   			
	   		<!-- <td><%#= image_tag property.image_url(:thumb)%></td> -->
	   	</tr>
	 </tr>
	<% end %>
</table>

<!-- </div> -->

<div class="col-md-12"> 
    <div class="pull-right">
        <div class="pagination">
            <div class="page_info">
                <%= page_entries_info @properties %>
            </div>
            <div class="pagination_links">
                <%= will_paginate @properties, :container => false %>
            </div>
        </div>
    </div>
</div>

<script>
$(function(){
   $('#pagination a').attr('data-remote', 'true')
});
</script>


<style type="text/css">
	.new{
		    float: right;
		margin: -40px -198%;
	}
</style>

app/views/__admin/properties/index.html.erb
<% render 'admin/properties/table'%>

app/views/__admin/properties/index.js.erb
jQuery('#properties').html(" 'admin/properties/index' )%>");
$('#pagination a').attr('data-remote', 'true');

app/views/__admin/properties/new.html.erb
<%= render "form2"%>

<!-- property area -->
<!-- <div class="content-area home-area-1 recent-property" style="background-color: #FCFCFC; padding-bottom: 55px;">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1 col-sm-12 text-center page-title">
                <! /.feature title -->
                <!-- <h2>Top submitted property</h2> -->
          <!--       <p>Nulla quis dapibus nisl. Suspendisse ultricies commodo arcu nec pretium. Nullam sed arcu ultricies . </p>
            </div>
        </div>
    </div>
</div> -->

app/views/properties/_form.html.erb
<%= form_for @property do |pr| %>
	<div>
		<%= pr.label :name, "Property Name"%>
		<%= pr.text_field :name, required: true %>
	</div>

	<div>
		<%= pr.label :category_id, "Property Type"%>
		<%= pr.select :category_id, Category.order("name ASC").map {|pt| [pt.name, pt.id]},:prompt =>"Select Category", required: true %>
	</div>

	<div>
		<%= pr.label :desc, "Description" %>
		<%= pr.text_field :desc ,required: true %>
	</div>

	<div>
		<%= pr.label :price, "Price" %>
		<%= pr.number_field :price, required: true %>
	</div>

	<div>
		<%= pr.label :size, "Size" %>
		<%= pr.text_field :size, required: true, :placeholder=>"100-200 sqft"%>
	</div>

	<div>
		<%= pr.label :price_sqft, "Price/Sqft"%>
		<%= pr.text_field :price_sqft, required: true, :placeholder=>"price per sqft" %>
	</div>

	<div>
		<%= pr.label :bhk, "BHK" %>
		<%= pr.text_field :bhk, required: true, :placeholder=>"1 BHK"%>
	</div>

	<div>
		<%= pr.label :city, "City"%>
		<%= pr.text_field :city, required: true %>
	</div>

	<div>
		<%= pr.label :status, "Status"%>
		<%= pr.text_field :status%>
	</div>


	<div>
		<%= pr.label :sales_type, "Sales Type" %>
		<%= pr.text_field :sales_type, required: true %>
	</div>

	<div>
		<%= pr.label :project_address, "Project Address"%>
		<%= pr.text_field :project_address, required: true%>
	</div>

	<div>
		<%= pr.label :image, "Property Image"%>
		<%= pr.file_field :image, required: true %>
		<% if pr.object.image? %>
		  <%= image_tag pr.object.image.thumb.url %>
		  <%= pr.label :remove_image %>
		  <%= pr.check_box :remove_image %>
		<% end %>
	</div>

	<div>
		<%= pr.label :builder_name, "Builder Name"%>
		<%= pr.text_field :builder_name,required: true%>
	</div>

	<div>
		<%= pr.submit "Save"%>
	</div>

<% end %>


 <script>
  $( function() {
    $( ".datepicker" ).datepicker();
  } );
  </script>

app/views/properties/_form2.html.erb
<h4 class="info-text"> New Property </h4>
<%= form_for @property do |pr| %>
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-3">
                <div class="form-group">
                   <%= pr.label :name, "Property Name:"%>
                   <%= pr.text_field :name ,required: true, class: "form-control" %>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :size, "Sqft:"%>
                    <%= pr.text_field :size, class: "form-control"%>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :price, "Price"%>
                    <%= pr.text_field :price, class: "form-control" %>
                </div>
            </div>

             <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :category_id, "Property Type"%>
                    <%= pr.select :category_id, Category.order("name ASC").map {|pt| [pt.name, pt.id]},class: "form-control", :prompt =>"--Select--" %> </span>
                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :price_sqft, "Price/Per Sqft:" %>
                    <%= pr.text_field :price_sqft, class: "form-control"%>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :bhk, "BHK:" %>
                    <%= pr.text_field :bhk, class: "form-control"%>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :city, "City:" %>
                    <%= pr.text_field :city, class: "form-control"%>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :bedroom, "Bedroom:" %>
                    <%= pr.text_field :bedroom, class: "form-control"%>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :bathroom, "Bathroom:" %>
                    <%= pr.text_field :bathroom, class: "form-control"%>
                </div>
            </div>


            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :toilet, "Toilet:" %>
                    <%= pr.text_field :toilet, class: "form-control"%>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :locality, "Locality:" %>
                    <%= pr.text_field :locality, class: "form-control"%>
                </div>
            </div>
        </div>
    </div>
<hr>
<h4>Building Details:</h4>
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :status, "Project Status" %>
                    <%#= pr.text_field :status, class: "form-control"%>
                    <%= select_tag :status,  options_from_collection_for_select(Property::ENUM_ENTITY, :last, :first ), { :prompt => "Select Status"} %>

                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :sales_type, "Sale Type:" %>
                    <%= pr.text_field :sales_type, class: "form-control"%>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :builder_name, "Builder Name:" %>
                    <%= pr.text_field :builder_name, class: "form-control"%>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :project_address, "Project Address:" %>
                    <%= pr.text_field :project_address, class: "form-control"%>
                </div>
            </div>
        </div>
    </div>
    
    
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-6">
                <div class="form-group">
                    <%= pr.label :desc, "Property Description:"%>
                    <%= pr.text_field :desc, class: "form-control"%>
                </div>
            </div>
        <!-- </div> -->
            <div class="col-sm-3">
                <div class="form-group">
                    <%= pr.label :image, "Property Image"%>
                    <%= pr.file_field :image, required: true, class: "form-control" %>
                    <% if pr.object.image? %>
                      <%= image_tag pr.object.image.thumb.url %>
                      <%= pr.label :remove_image %>
                      <%= pr.check_box :remove_image %>
                    <% end %>
                </div>
            </div>
            <div class="col-sm-3">
                <!-- <div class="form-group"> -->
                    <div class="submit">
                        <%= pr.submit "Create", class: 'navbar-btn nav-button wow bounceInRight'  %>
                      <%#= pr.submit 'Save'%>
                    </div>                
                <!-- </div> -->
                
            </div>
        </div>
    </div>
    
    <!-- <div class="submit"> -->
        <%#= pr.submit "Submit", class: 'navbar-btn nav-button wow bounceInRight'  %>
      <%#= pr.submit 'Save'%>
    <!-- </div> -->
    
<% end %>

<style>
    .submit{
        width: 87px;
    padding-top: 21px;
    margin-left: 29%;
    margin-bottom: 10%;
    }
</style>

app/views/properties/index.html.erb
<%= render 'property2'%>
<%#= link_to "New Category", new_category_path %>
<%#= link_to "New Property", new_property_path %>

<!-- <h2>Properties</h2> -->
<!-- <table>
	<thead>
		<tr>
			<th>Project Name</th>
			<th>Project Type</th>
			<th>Price</th>
			<th>Price/Sqft</th>
			<th>BHK</th>
			<th>Image</th>
			<th>Size</th>
		</tr>
	</thead>
	<tbody>
		<%# for property in @properties %>
		  <tr>
			<td><%#= property.name%></td>
			<td><%# category = Category.find_by(id: property.category_id)%><%#= category.name%></td>
			<td><%#= property.price%></td>
			<td><%#= property.price_sqft%></td>
			<td><%#= property.bhk %></td>
			<td><%#= image_tag property.image_url(:thumb)%></td>
			<td><%#= property.size%></td>
		  </tr>
		<%# end %>
	</tbody>
</table> -->

app/views/properties/index.js.erb
jQuery('#properties').html(" 'properties/index' )%>");
$('#pagination a').attr('data-remote', 'true');

app/views/properties/new.html.erb
<%= render "form2"%>

<!-- property area -->
<!-- <div class="content-area home-area-1 recent-property" style="background-color: #FCFCFC; padding-bottom: 55px;">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1 col-sm-12 text-center page-title">
                <! /.feature title -->
                <!-- <h2>Top submitted property</h2> -->
          <!--       <p>Nulla quis dapibus nisl. Suspendisse ultricies commodo arcu nec pretium. Nullam sed arcu ultricies . </p>
            </div>
        </div>
    </div>
</div> -->