config/routes.rb
Rails.application.routes.draw do
 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'about_us/index'

  # get 'enquires/index'

 get 'faqs/index'

 get 'terms/index'

 get 'abouts/index'

 get 'messages/new'

 devise_for :users
 resources :properties
 resources :homes
 resources :messages
 resources :accounts
 resources :abouts
 resources :contacts
 resources :properties
 resources :categories
 resources :enquirey
 resources :enquiries

 
 # namespace :admin do
 # 	resources :categories, only: [:index, :update, :edit, :new, :create], controller: '/admin/categories', action:'new' 
 # 	resources :admins
 # 	resources :properties, only: [:index, :update, :edit, :new]

 # end

 get 'accounts/user'

 root "homes#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :properties
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/enquirey.rb
class Enquirey < ApplicationRecord
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord

	def full_name
	  self.first_name + self.last_name
	end
end

app/models/news_feed.rb
class NewsFeed < ApplicationRecord
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :category

  mount_uploader :image, ImageUploader

  validates_processing_of :image
  
  

  enum status: [:active, :inactive]
  ENUM_ENTITY = {"active" => 1, "inactive" => 0}

  scope :property, lambda{|property| where("concat(city, bhk, price) like ?", "%#{property}%").presence || all }

  # def self.search(search)
  # 	if search
  # 		where('locality LIKE ?', "%#{search}%")
  #     # Property.where('city ILIKE :query OR bhk ILIKE :query OR price ILIKE :query', query: "%#{query}%")

  # 		# where('city LIKE ? ', "%#{property}%").having("expenses.category = 1")
  # 	else
  # 		all
  # 	end
  # end

  def self.search(search)
    # where("locality LIKE ?", "%#{search}%").having("properties.status = 1")
    where("locality LIKE ?", "%#{search}%")
  end


  private
	
	def image_size_validation
	   errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
	end
end

app/models/query.rb
class Query < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :new_category
  
  def index
  	# @category = Category.all
    categories = Category.all if params[:page].nil?
    @categories = categories.page(params[:page])
    # @categories = categories.page(params[:page]).per_page(5)
  end

  def show
    @category = Category.find_by(id: params[:id])
  end

  # def create
  # 	@category = Category.new(category_params)
  # 	respond_to do |format|
  # 	  if @category.save
  # 	  	format.json {render json: @category, status: :ok }
  # 	  	format.js 
  # 	  	format.html {redirect_to admin_categories_path, flash: {success: "Category Saved Successfully"}}
  # 	  else
  # 	  	format.json {render json: @category.errors.full_messages, status: :unprocessable_entity}
  # 	  	format.js
  # 	  	format.html {redirect_to admin_categories_path, flash: {error: @category.errors.full_messages }}
  # 	  end
  # 	end
  # end

private

  def category_params
  	params.require(:category).permit(:name, :desc, :is_stock)
  end

  def new_category
  	@category = Category.new
  end

end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/enquires_helper.rb
module EnquiresHelper
end

app/helpers/enquirey_helper.rb
module EnquireyHelper
end

app/helpers/enquiry_helper.rb
module EnquiryHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/__admin/categories/_form.html.erb
 <style>
    #reg{
            width: 106px;
    float: right;
    }
</style>

<div class="container">
  <div class="col-md-6">
      <div class="box-for overflow">                         
          <div class="col-md-12 col-xs-12 login-blocks">
              <!-- <h2>Login : </h2>  -->

                  <%= form_for :category, html: {class: 'finance_form'}, method: :post, remote: true do |c| %>
                    <div class="form-group">
                        <%= c.label :name, "Category Name:" %>
                        <%= c.text_field :name, required: true, class: "form-control"%>
                    </div>

                    <div class="form-group">
                        <%= c.label :desc, "Description"%>
                        <%= c.text_field :desc, required: true,class: "form-control"%>
                    </div>

                    <div class="form-group">
                        <%= c.label :is_stock, "Status"%>
                        <%= c.text_field :is_stock, required: true,class: "form-control"%>
                    </div>

                    <div  class="text-center" id="reg">
                        <%= c.submit "Save",class: "btn btn-default"%>
                    </div>
                  <% end %>

          </div>
          
      </div>
  </div>

</div>

app/views/__admin/categories/_form2.html.erb
<h4>New Category</h4>
<%= form_for Category.new do |c|%>
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-3">
                <div class="form-group">
                    <%= c.label :name, "Category Name:"%>
                    <%= c.text_field :name, class: "form-control"%>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <%= c.label :desc, "Category Description"%>
                    <%= c.text_field :desc, required: true, class: "form-control" %>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <%= c.label :is_stock, "Ststus:"%>
                    <%= c.text_field :is_stock, required: true, class: "form-control" %>
                </div>
            </div>
        </div>

        <div class="col-sm-3">
            <div class="submit">
                <%= c.submit "Create", class: 'navbar-btn nav-button wow bounceInRight'  %>
            </div>                
            
        </div>
    </div>
<% end %>


<style>
    .submit{
            width: 82px;
    margin-left: 339%;
    margin-top: -12%;
    margin-bottom: 10%;
    }
</style>

app/views/__admin/categories/_half.html.erb
 <style>
    #reg{
            width: 106px;
    float: right;
    }
</style>

   <div class="page-head"> 
      <div class="container">
          <div class="row">
              <div class="page-head-content">
                  <h1 class="page-title">Home New account / Sign in </h1>               
              </div>
          </div>
      </div>
  </div>


  <div class="register-area" style="background-color: rgb(249, 249, 249);">
      <div class="container">
          <div class="col-md-6">
              <div class="box-for overflow">                         
                  <div class="col-md-12 col-xs-12 login-blocks">
                      <h2>Login : </h2> 

                      <%= render 'devise/sessions/login'%>
                      <%= render "devise/shared/links" %>
                      <br>
                      
                      <h2>Social login :  </h2> 
                      
                      <p>
                      <a class="login-social" href="#"><i class="fa fa-facebook"></i>&nbsp;Facebook</a> 
                      <a class="login-social" href="#"><i class="fa fa-google-plus"></i>&nbsp;Gmail</a> 
                      <a class="login-social" href="#"><i class="fa fa-twitter"></i>&nbsp;Twitter</a>  
                      </p> 
                  </div>
                  
              </div>
          </div>

      </div>
  </div>      

app/views/__admin/categories/_popup.html.erb
 <div class="col-md-3">
      <button type="button" class= "btn btn-outline-primary btn-md" data-toggle="modal" data-target="#ModalAddFinance">Add new bill</button>
  </div>



<!-- Modal -->
<div class="modal fade" id="ModalAddFinance" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Finance Transaction</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="errors_invoice">
        </div>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/__admin/categories/_table.html.erb
<div class="">
    <div class="title-line wow fadeInRight animated"></div>
</div>
<div class="row wow fadeInRight animated">
    <div class="col-sm-6">
        <p class="author-category">
            <a href="#">Categories</a>
        </p>
    </div>
    <div class="col-sm-6 right" >
            <%= link_to "New Category", new_admin_category_path %>
       <!--  <p class="date-comments">
            <a href="single.html"><i class="fa fa-comment-o"></i> 8 Comments</a>
        </p> -->
    </div>
</div> 




<table border=1 style="text-align: center; width: 310%;">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Status</th>
		<th>Action</th>
	</tr>
	<% for category in @categories%>
	<tr>
		<tr>
			<td><%= link_to category.name, edit_admin_category_path(category) %></td>
			<td><%= category.desc %></td>
			<td><%= link_to category.is_stock, edit_admin_category_path(category) %></td>
			<td></td>
			<!-- <td><img class="img_class" src="<%#= product.img %>"></td> -->
		</tr>
	</tr>
	<% end %>
</table>

<!-- </div> -->

<div class="col-md-12"> 
    <div class="pull-right">
        <div class="pagination">
            <div class="page_info">
                <%= page_entries_info @categories %>
            </div>
            <div class="pagination_links">
                <%= will_paginate @categories, :container => false %>
            </div>
        </div>
    </div>
</div>



<script>
$(function(){
   $('#pagination a').attr('data-remote', 'true')
});
</script>

<style type="text/css">
	.new{
		    float: right;
		margin: -40px -198%;
	}
</style>

app/views/__admin/categories/create.js.erb
toastr.options = {
  "closeButton": false,
  "debug": false,
  "newestOnTop": false,
  "progressBar": false,
  "positionClass": "toast-top-full-width",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "100",
  "hideDuration": "5000",
  "timeOut": "5000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}
<% if  @category.errors.empty? %>
  $('.finance_form')[0].reset();
  $('#ModalAddFinance').modal('hide');
    toastr["success"]('New Bill has been generated successfully.')
   setTimeout(function(){
    window.location.reload(true);
    }, 2000);
<%else%>
  $('.errors_invoice').append('<p class = "error_msg" ><%= @category.errors.full_messages.join(' , ') %></p>');
  setTimeout(function(){
      $('.error_msg').remove();
    }, 3000);
<%end%>

app/views/__admin/categories/edit.html.erb
<%#= render 'admin/categories/form'%>

<div class="page-head"> 
  <div class="container">
      <div class="row">
          <div class="page-head-content">
              <h1 class="page-title">User Account Details</h1>               
          </div>
      </div>
  </div>
</div>
<div class="content-area blog-page padding-top-40" style="background-color: #FCFCFC; padding-bottom: 55px;">
    <div class="container">
        <div class="row">
            <div class="blog-asside-right col-md-3">
                <div class="panel panel-default sidebar-menu wow fadeInRight animated" >
                    <div class="panel-heading">
                        <h3 class="panel-title"> Account</h3>
                        <ul class="nav nav-tabs tabs-left sideways">
                            <!-- <li class="active"><a href="#home-v" data-toggle="tab">Home</a></li> -->
                            <li class="active"><a href="#category-v" data-toggle="tab">Category</a></li>
                            <li class="panel-title"><a href="#properties-v" data-toggle="tab">Properties</a></li>
                            <li class="panel-title"><a href="#settings-v" data-toggle="tab">Settings</a></li>
                        </ul>
                    </div>
                </div>
            </div>   
            
            <div class="blog-lst col-md-9 p0">
                <section id="id-100" class="post single">

                  <div id="post-content" class="post-body single wow fadeInLeft animated">
                      <div  class="col-sm-6">
                       <!--  <h3>User Account</h3>
                        <hr/> -->
                        <div class="col-xs-9">
                          <div class="tab-content">
                            <div class="tab-pane active" id="home-v">

                            </div>
                            
                            <div class="tab-pane" id="category-v">
                    	    
                    	      <h4 class="wow fadeInLeft animated">Edit Category</h4>
                              <%= render 'admin/categories/edit_form'%>
                            
                            </div>
                            
                            <div class="tab-pane" id="properties-v">
                               <%#= render 'admin/properties/index'%>
                            </div>
                            
                            <div class="tab-pane" id="settings-v">

                            </div>
                          </div>
                        </div>

                        <div class="clearfix"></div>

                      </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>






<style>
.tabs-left, .tabs-right {
  border-bottom: none;
  padding-top: 2px;
}
.tabs-left {
  border-right: 1px solid #ddd;
}
.tabs-right {
  border-left: 1px solid #ddd;
}
.tabs-left>li, .tabs-right>li {
  float: none;
  margin-bottom: 2px;
}
.tabs-left>li {
  margin-right: -1px;
}
.tabs-right>li {
  margin-left: -1px;
}
.tabs-left>li.active>a,
.tabs-left>li.active>a:hover,
.tabs-left>li.active>a:focus {
  border-bottom-color: #ddd;
  border-right-color: transparent;
}

.tabs-right>li.active>a,
.tabs-right>li.active>a:hover,
.tabs-right>li.active>a:focus {
  border-bottom: 1px solid #ddd;
  border-left-color: transparent;
}
.tabs-left>li>a {
  border-radius: 4px 0 0 4px;
  margin-right: 0;
  display:block;
}
.tabs-right>li>a {
  border-radius: 0 4px 4px 0;
  margin-right: 0;
}
</style>

app/views/__admin/categories/index.html.erb
<%= render 'admin/categories/table'%>

app/views/__admin/categories/index.js.erb
jQuery('#categories').html(" 'admin/categories/index' )%>");
$('#pagination a').attr('data-remote', 'true');

app/views/__admin/categories/new.html.erb
<%#= render "form"%>
<%#= render 'admin/categories/form'%>

<div class="page-head"> 
  <div class="container">
      <div class="row">
          <div class="page-head-content">
              <h1 class="page-title">User Account Details</h1>               
          </div>
      </div>
  </div>
</div>
<div class="content-area blog-page padding-top-40" style="background-color: #FCFCFC; padding-bottom: 55px;">
    <div class="container">
        <div class="row">
            <div class="blog-asside-right col-md-3">
                <div class="panel panel-default sidebar-menu wow fadeInRight animated" >
                    <div class="panel-heading">
                        <h3 class="panel-title"> Account</h3>
                        <ul class="nav nav-tabs tabs-left sideways">
                            <!-- <li class="active"><a href="#home-v" data-toggle="tab">Home</a></li> -->
                            <li class="active"><a href="#category-v" data-toggle="tab">Category</a></li>
                            <li class="panel-title"><a href="#properties-v" data-toggle="tab">Properties</a></li>
                            <li class="panel-title"><a href="#settings-v" data-toggle="tab">Settings</a></li>
                        </ul>
                    </div>
                </div>
            </div>   
            
            <div class="blog-lst col-md-9 p0">
                <section id="id-100" class="post single">

                  <div id="post-content" class="post-body single wow fadeInLeft animated">
                      <div  class="col-sm-6">
                       <!--  <h3>User Account</h3>
                        <hr/> -->
                        <div class="col-xs-9">
                          <div class="tab-content">
                            <div class="tab-pane active" id="home-v">

                            </div>
                            
                            <div class="tab-pane" id="category-v">
                    	    
                    	      <h4 class="wow fadeInLeft animated">New Category</h4>
                              <%= render 'admin/categories/form'%>
                            
                            </div>
                            
                            <div class="tab-pane" id="properties-v">
                               <%#= render 'admin/properties/index'%>
                            </div>
                            
                            <div class="tab-pane" id="settings-v">

                            </div>
                          </div>
                        </div>

                        <div class="clearfix"></div>

                      </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>






<style>
.tabs-left, .tabs-right {
  border-bottom: none;
  padding-top: 2px;
}
.tabs-left {
  border-right: 1px solid #ddd;
}
.tabs-right {
  border-left: 1px solid #ddd;
}
.tabs-left>li, .tabs-right>li {
  float: none;
  margin-bottom: 2px;
}
.tabs-left>li {
  margin-right: -1px;
}
.tabs-right>li {
  margin-left: -1px;
}
.tabs-left>li.active>a,
.tabs-left>li.active>a:hover,
.tabs-left>li.active>a:focus {
  border-bottom-color: #ddd;
  border-right-color: transparent;
}

.tabs-right>li.active>a,
.tabs-right>li.active>a:hover,
.tabs-right>li.active>a:focus {
  border-bottom: 1px solid #ddd;
  border-left-color: transparent;
}
.tabs-left>li>a {
  border-radius: 4px 0 0 4px;
  margin-right: 0;
  display:block;
}
.tabs-right>li>a {
  border-radius: 0 4px 4px 0;
  margin-right: 0;
}
</style>

app/views/categories/_form.html.erb
 <style>
    #reg{
            width: 106px;
    float: right;
    }
</style>

<div class="container">
  <div class="col-md-6">
      <div class="box-for overflow">                         
          <div class="col-md-12 col-xs-12 login-blocks">
              <!-- <h2>Login : </h2>  -->

                  <%= form_for :category, html: {class: 'finance_form'}, method: :post, remote: true do |c| %>
                    <div class="form-group">
                        <%= c.label :name, "Category Name:" %>
                        <%= c.text_field :name, required: true, class: "form-control"%>
                    </div>

                    <div class="form-group">
                        <%= c.label :desc, "Description"%>
                        <%= c.text_field :desc, required: true,class: "form-control"%>
                    </div>

                    <div class="form-group">
                        <%= c.label :is_stock, "Status"%>
                        <%= c.text_field :is_stock, required: true,class: "form-control"%>
                    </div>

                    <div  class="text-center" id="reg">
                        <%= c.submit "Save",class: "btn btn-default"%>
                    </div>
                  <% end %>

          </div>
          
      </div>
  </div>

</div>

app/views/categories/_form2.html.erb
<h4>New Category</h4>
<%= form_for Category.new do |c|%>
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-3">
                <div class="form-group">
                    <%= c.label :name, "Category Name:"%>
                    <%= c.text_field :name, class: "form-control"%>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <%= c.label :desc, "Category Description"%>
                    <%= c.text_field :desc, required: true, class: "form-control" %>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <%= c.label :is_stock, "Ststus:"%>
                    <%= c.text_field :is_stock, required: true, class: "form-control" %>
                </div>
            </div>
        </div>

        <div class="col-sm-3">
            <div class="submit">
                <%= c.submit "Create", class: 'navbar-btn nav-button wow bounceInRight'  %>
            </div>                
            
        </div>
    </div>
<% end %>


<style>
    .submit{
            width: 82px;
    margin-left: 339%;
    margin-top: -12%;
    margin-bottom: 10%;
    }
</style>

app/views/categories/_half.html.erb
 <style>
    #reg{
            width: 106px;
    float: right;
    }
</style>

   <div class="page-head"> 
      <div class="container">
          <div class="row">
              <div class="page-head-content">
                  <h1 class="page-title">Home New account / Sign in </h1>               
              </div>
          </div>
      </div>
  </div>


  <div class="register-area" style="background-color: rgb(249, 249, 249);">
      <div class="container">
          <div class="col-md-6">
              <div class="box-for overflow">                         
                  <div class="col-md-12 col-xs-12 login-blocks">
                      <h2>Login : </h2> 

                      <%= render 'devise/sessions/login'%>
                      <%= render "devise/shared/links" %>
                      <br>
                      
                      <h2>Social login :  </h2> 
                      
                      <p>
                      <a class="login-social" href="#"><i class="fa fa-facebook"></i>&nbsp;Facebook</a> 
                      <a class="login-social" href="#"><i class="fa fa-google-plus"></i>&nbsp;Gmail</a> 
                      <a class="login-social" href="#"><i class="fa fa-twitter"></i>&nbsp;Twitter</a>  
                      </p> 
                  </div>
                  
              </div>
          </div>

      </div>
  </div>      

app/views/categories/_new.html.erb
<%#= render "form"%>
<%#= render 'admin/categories/form'%>

<div class="page-head"> 
  <div class="container">
      <div class="row">
          <div class="page-head-content">
              <h1 class="page-title">User Account Details</h1>               
          </div>
      </div>
  </div>
</div>
<div class="content-area blog-page padding-top-40" style="background-color: #FCFCFC; padding-bottom: 55px;">
    <div class="container">
        <div class="row">
            <div class="blog-asside-right col-md-3">
                <div class="panel panel-default sidebar-menu wow fadeInRight animated" >
                    <div class="panel-heading">
                        <h3 class="panel-title"> Account</h3>
                        <ul class="nav nav-tabs tabs-left sideways">
                            <!-- <li class="active"><a href="#home-v" data-toggle="tab">Home</a></li> -->
                            <li class="active"><a href="#category-v" data-toggle="tab">Category</a></li>
                            <li class="panel-title"><a href="#properties-v" data-toggle="tab">Properties</a></li>
                            <li class="panel-title"><a href="#settings-v" data-toggle="tab">Settings</a></li>
                        </ul>
                    </div>
                </div>
            </div>   
            
            <div class="blog-lst col-md-9 p0">
                <section id="id-100" class="post single">

                  <div id="post-content" class="post-body single wow fadeInLeft animated">
                      <div  class="col-sm-6">
                       <!--  <h3>User Account</h3>
                        <hr/> -->
                        <div class="col-xs-9">
                          <div class="tab-content">
                            <div class="tab-pane active" id="home-v">

                            </div>
                            
                            <div class="tab-pane" id="category-v">
                    	    
                    	      <h4 class="wow fadeInLeft animated">New Category</h4>
                              <%= render 'admin/categories/form'%>
                            
                            </div>
                            
                            <div class="tab-pane" id="properties-v">
                               <%#= render 'admin/properties/index'%>
                            </div>
                            
                            <div class="tab-pane" id="settings-v">

                            </div>
                          </div>
                        </div>

                        <div class="clearfix"></div>

                      </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>






<style>
.tabs-left, .tabs-right {
  border-bottom: none;
  padding-top: 2px;
}
.tabs-left {
  border-right: 1px solid #ddd;
}
.tabs-right {
  border-left: 1px solid #ddd;
}
.tabs-left>li, .tabs-right>li {
  float: none;
  margin-bottom: 2px;
}
.tabs-left>li {
  margin-right: -1px;
}
.tabs-right>li {
  margin-left: -1px;
}
.tabs-left>li.active>a,
.tabs-left>li.active>a:hover,
.tabs-left>li.active>a:focus {
  border-bottom-color: #ddd;
  border-right-color: transparent;
}

.tabs-right>li.active>a,
.tabs-right>li.active>a:hover,
.tabs-right>li.active>a:focus {
  border-bottom: 1px solid #ddd;
  border-left-color: transparent;
}
.tabs-left>li>a {
  border-radius: 4px 0 0 4px;
  margin-right: 0;
  display:block;
}
.tabs-right>li>a {
  border-radius: 0 4px 4px 0;
  margin-right: 0;
}
</style>

app/views/categories/_popup.html.erb
 <div class="col-md-3">
      <button type="button" class= "btn btn-outline-primary btn-md" data-toggle="modal" data-target="#ModalAddFinance">Add new bill</button>
  </div>



<!-- Modal -->
<div class="modal fade" id="ModalAddFinance" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Finance Transaction</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="errors_invoice">
        </div>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/categories/_table.html.erb
<div class="">
    <div class="title-line wow fadeInRight animated"></div>
</div>
<div class="row wow fadeInRight animated">
    <div class="col-sm-6">
        <p class="author-category">
            <a href="#">Categories</a>
        </p>
    </div>
    <div class="col-sm-6 right" >
            <%= link_to "New Category", new_admin_category_path %>
       <!--  <p class="date-comments">
            <a href="single.html"><i class="fa fa-comment-o"></i> 8 Comments</a>
        </p> -->
    </div>
</div> 




<table border=1 style="text-align: center; width: 310%;">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Status</th>
		<th>Action</th>
	</tr>
	<% for category in @categories%>
	<tr>
		<tr>
			<td><%= link_to category.name, edit_admin_category_path(category) %></td>
			<td><%= category.desc %></td>
			<td><%= link_to category.is_stock, edit_admin_category_path(category) %></td>
			<td></td>
			<!-- <td><img class="img_class" src="<%#= product.img %>"></td> -->
		</tr>
	</tr>
	<% end %>
</table>

<!-- </div> -->

<div class="col-md-12"> 
    <div class="pull-right">
        <div class="pagination">
            <div class="page_info">
                <%#= page_entries_info @categories %>
            </div>
            <div class="pagination_links">
                <%= will_paginate @categories, :container => false %>
            </div>
        </div>
    </div>
</div>



<script>
$(function(){
   $('#pagination a').attr('data-remote', 'true')
});
</script>

<style type="text/css">
	.new{
		    float: right;
		margin: -40px -198%;
	}
</style>

app/views/categories/create.js.erb
toastr.options = {
  "closeButton": false,
  "debug": false,
  "newestOnTop": false,
  "progressBar": false,
  "positionClass": "toast-top-full-width",
  "preventDuplicates": false,
  "onclick": null,
  "showDuration": "100",
  "hideDuration": "5000",
  "timeOut": "5000",
  "extendedTimeOut": "1000",
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut"
}
<% if  @category.errors.empty? %>
  $('.finance_form')[0].reset();
  $('#ModalAddFinance').modal('hide');
    toastr["success"]('New Bill has been generated successfully.')
   setTimeout(function(){
    window.location.reload(true);
    }, 2000);
<%else%>
  $('.errors_invoice').append('<p class = "error_msg" ><%= @category.errors.full_messages.join(' , ') %></p>');
  setTimeout(function(){
      $('.error_msg').remove();
    }, 3000);
<%end%>

app/views/categories/index.html.erb
<%= render 'admin/categories/table'%>

app/views/categories/index.js.erb
jQuery('#categories').html(" 'admin/categories/index' )%>");
$('#pagination a').attr('data-remote', 'true');

app/views/categories/new.html.erb
<%= render 'categories/form'%>

app/views/categories/show.html.erb
<h1>Welcome</h1>